dist: bionic

language: c

notifications:
 - email: true

before_script:
 - sudo apt-get install linux-headers-$(uname -r)
 - git clone --branch=exfat-next https://github.com/namjaejeon/exfat_oot
 - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
 - export PATH=/usr/local/lib:$PATH

script:
 - ./autogen.sh > /dev/null
 - ./configure > /dev/null
 - make -j$((`nproc`+1)) > /dev/null
 - sudo make install > /dev/null
 - cd exfat_oot
 - make > /dev/null
 - sudo make install > /dev/null
 - sudo modprobe exfat
 - sudo mkdir -p /mnt/test
 # create file/director test
 - truncate -s 10G test.img
 - sudo losetup /dev/loop22 test.img
 - sudo mkfs.exfat /dev/loop22
 - sudo mount -t exfat /dev/loop22 /mnt/test/
 - cd /mnt/test/
 - i=1;while [ $i -le 10000 ];do sudo touch file$i;if [ $? != 0 ]; then exit 1; fi; i=$(($i + 1));done
 - sync
 - sudo rm -rf *
 - i=1;while [ $i -le 10000 ];do sudo mkdir file$i;if [ $? != 0 ]; then exit 1; fi; i=$(($i + 1));done
 - sync
 - sudo rm -rf *
 - sudo fsck.exfat /dev/loop22
 - cd -
