markdown: kramdown
baseurl: /Jool
repository-url: https://github.com/NICMx/Jool
latest-version: 4.1.11

rfc-siit: https://tools.ietf.org/html/rfc7915
draft-siit-eam: https://tools.ietf.org/html/rfc7757
draft-siit-dc: https://tools.ietf.org/html/rfc7755
draft-siit-dc-2xlat: https://tools.ietf.org/html/rfc7756
draft-nat64-port-allocation: https://tools.ietf.org/html/draft-ietf-sunset4-nat64-port-allocation-02
draft-deprecate-atomfrag-generation: https://tools.ietf.org/html/rfc8021
